class laptop:
    price=0
    proc=""
    ram=""
hp=laptop()
dell=laptop()
lenovo=laptop()
hp.price=50000
hp.proc="i5"
hp.ram="15GB"
dell.price=60000
dell.proc="i7"
dell.ram="16GB"
lenovo.price=80000
lenovo.proc="i8"
lenovo.ram="19GB"
print(hp.price)
print(dell.price)
print(lenovo.price)
